### PR TITLE
#16290977 Users should be able to login

### PR DESCRIPTION
**Pull request by malfahad**
#### What does this Pr do?
- Adds an implementation to enable users to Login

#### Description of the task to be implemented.
- Create a Login component with argon CSS classes.
- Create actions and reducers for redux.
- Implement login functionality with `fetch API`
- test all code

#### How can this be manually tested?
- Fetch this branch to your local machine using `git fetch origin ft-user-login-162909781`
- Checkout into this branch using `git checkoutft-user-login-162909781`
- Install project dependencies by running `npm install`
- Run the development server by running `npm start`
- Once the browser opens, navigate to either `/login` and login with a registered account.

#### Relvant pivotal stories.
[#162909781](https://www.pivotaltracker.com/story/show/162909781)

### CODE REVIEW

**Comment by armstrongsouljah** [comment]
> What is new in this PR
> 
> * Added login functionality at the `/login` endpoint
> * moved assets from src folder to dist folder. src folder is tested for cov.

Make it a bit more descriptive.

**Comment by malfahad** [comment]
I moved the assets from the `/src` to `/dist` folder. This is because the `/src` folder has functionality code that will be tested.

**Review by MuhweziDeo — APPROVED** [review]
too many files changed

**Review by kdaglas — APPROVED** [review]
i have tested it and it is good to go...

**Review by mariamiah — APPROVED** [review]
LGTM

**Pull request merged**
